insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Pajero', 'V12', 'diisel', 344, '/ultrices/posuere/cubilia.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Pontiac', '1000', 'V8', 'diisel', 229, '/pede/posuere/nonummy.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Aston Martin', 'DBS', 'V6', 'elekter', 509, '/a/odio/in/hac/habitasse/platea.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'S-Class', 'V8', 'elekter', 277, '/at/ipsum/ac/tellus.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Audi', 'A5', 'V8', 'diisel', 692, '/nec/nisi/vulputate/nonummy/maecenas/tincidunt.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'F-Series', 'V8', 'bensiin', 852, '/vel/nisl/duis.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Lincoln', 'Town Car', 'V6', 'elekter', 360, '/tempus/vel/pede/morbi/porttitor/lorem.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Explorer', 'V12', 'gaas', 444, '/purus.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Explorer Sport Trac', 'V8', 'elekter', 427, '/nascetur/ridiculus/mus/etiam.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Toyota', 'Corolla', 'V12', 'gaas', 248, '/vitae/quam/suspendisse/potenti/nullam/porttitor.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Cadillac', 'DTS', 'V12', 'diisel', 553, '/eu/felis/fusce/posuere/felis/sed/lacus.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Mustang', 'V12', 'bensiin', 502, '/morbi/non.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Nissan', 'Altima', 'V12', 'diisel', 979, '/habitasse/platea/dictumst/etiam/faucibus.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Lancer Evolution', 'V12', 'diisel', 565, '/sapien/ut/nunc/vestibulum/ante/ipsum.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Volvo', 'S60', 'V12', 'bensiin', 156, '/quam/sapien/varius/ut/blandit/non/interdum.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Crown Victoria', 'V8', 'bensiin', 297, '/nec.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('GMC', 'Envoy', 'V12', 'bensiin', 684, '/ac/nibh/fusce/lacus/purus/aliquet/at.png');
insert into autod (mark, model, engine, fuel, price, image) values ('MINI', 'Cooper Clubman', 'V6', 'diisel', 633, '/sit/amet.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Acura', 'NSX', 'V8', 'elekter', 102, '/maecenas/leo/odio/condimentum/id/luctus.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Chrysler', 'Imperial', 'V12', 'elekter', 822, '/proin/at/turpis/a/pede/posuere/nonummy.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Lexus', 'LX', 'V12', 'elekter', 308, '/potenti/in.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Lexus', 'RX Hybrid', 'V12', 'diisel', 307, '/convallis.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Explorer', 'V8', 'gaas', 396, '/non/velit.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Kia', 'Sorento', 'V8', 'bensiin', 336, '/in/ante/vestibulum/ante/ipsum/primis.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Cadillac', 'Seville', 'V6', 'diisel', 671, '/magna.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Hyundai', 'Tiburon', 'V8', 'diisel', 247, '/magnis/dis/parturient/montes/nascetur/ridiculus.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Lumina', 'V12', 'bensiin', 957, '/vestibulum/eget/vulputate.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Mazda', 'Mazda5', 'V6', 'elekter', 765, '/molestie/hendrerit/at.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Buick', 'Rainier', 'V8', 'diisel', 715, '/bibendum/felis/sed.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Acura', 'RL', 'V6', 'gaas', 438, '/id/consequat/in/consequat/ut/nulla.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Land Rover', 'Range Rover', 'V12', 'gaas', 216, '/a/feugiat/et/eros/vestibulum/ac/est.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Ranger', 'V6', 'elekter', 811, '/vitae/consectetuer/eget/rutrum.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Pontiac', 'Trans Sport', 'V6', 'gaas', 551, '/amet.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Chevrolet', 'G-Series 3500', 'V12', 'bensiin', 348, '/non/sodales/sed/tincidunt/eu/felis/fusce.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Toyota', '4Runner', 'V8', 'elekter', 871, '/est/donec/odio/justo/sollicitudin/ut.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'E350', 'V8', 'gaas', 733, '/ligula/nec/sem/duis/aliquam/convallis/nunc.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Express 2500', 'V12', 'gaas', 467, '/lacus.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Challenger', 'V12', 'diisel', 474, '/donec/odio/justo/sollicitudin/ut/suscipit.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Bentley', 'Continental Super', 'V12', 'elekter', 737, '/ante/vestibulum/ante/ipsum/primis.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Ferrari', '430 Scuderia', 'V12', 'diisel', 846, '/volutpat/in/congue.json');
