insert into autod (mark, model, engine, fuel, price, image) values ('Buick', 'LaCrosse', 'v12', 'bensiin', 540, '/erat/tortor/sollicitudin.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Nissan', 'Xterra', 'v12', 'elekter', 530, '/eros/vestibulum/ac/est.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Nissan', '370Z', 'v12', 'gaas', 912, '/lectus/in.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Lexus', 'IS F', 'v8', 'elekter', 312, '/blandit/lacinia/erat/vestibulum/sed/magna.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'E-Class', 'v6', 'diisel', 950, '/tincidunt/ante/vel/ipsum.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Escape', 'v8', 'gaas', 923, '/augue.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Lincoln', 'Continental', 'v12', 'diisel', 293, '/metus/sapien/ut.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Hummer', 'H2', 'v12', 'elekter', 340, '/sit/amet.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Hyundai', 'Azera', 'v12', 'elekter', 392, '/sagittis.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Express', 'v12', 'diisel', 165, '/cubilia/curae/mauris/viverra.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Volkswagen', 'riolet', 'v6', 'bensiin', 796, '/nulla/justo.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Eurovan', 'v8', 'gaas', 892, '/blandit.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Chrysler', 'LeBaron', 'v8', 'gaas', 815, '/congue/vivamus/metus/arcu/adipiscing/molestie/hendrerit.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Endeavor', 'v12', 'bensiin', 837, '/nulla/pede/ullamcorper/augue/a/suscipit.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Hyundai', 'Scoupe', 'v8', 'bensiin', 304, '/pretium.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Pontiac', 'Trans Sport', 'v12', 'bensiin', 100, '/lobortis.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Truck', 'v6', 'diisel', 677, '/turpis/donec/posuere/metus/vitae.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Dodge', 'Dakota', 'v8', 'elekter', 163, '/at/nunc/commodo/placerat.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Acura', 'TL', 'v12', 'diisel', 652, '/platea/dictumst/etiam/faucibus/cursus/urna/ut.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'GTO', 'v8', 'bensiin', 636, '/placerat/ante.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Honda', 'Accord', 'v8', 'elekter', 319, '/suspendisse/accumsan/tortor.jpg');
insert into autod (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Montero Sport', 'v8', 'gaas', 587, '/proin/at.aspx');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Freestyle', 'v6', 'diisel', 115, '/cubilia/curae/donec/pharetra/magna/vestibulum.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Nissan', 'Titan', 'v6', 'bensiin', 730, '/tempor/turpis/nec/euismod/scelerisque/quam.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Pontiac', 'G3', 'v6', 'diisel', 774, '/in/lectus/pellentesque/at.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'SL-Class', 'v6', 'bensiin', 104, '/primis/in/faucibus/orci.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Isuzu', 'i-370', 'v12', 'elekter', 722, '/lacinia/sapien/quis/libero/nullam/sit/amet.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Expedition', 'v12', 'diisel', 707, '/ornare/imperdiet/sapien/urna/pretium/nisl.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Suzuki', 'Aerio', 'v12', 'gaas', 715, '/quisque.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Type 2', 'v6', 'elekter', 455, '/at/diam/nam/tristique/tortor/eu/pede.json');
insert into autod (mark, model, engine, fuel, price, image) values ('GMC', 'Sierra 3500', 'v12', 'gaas', 655, '/sagittis/nam/congue/risus.html');
insert into autod (mark, model, engine, fuel, price, image) values ('Dodge', 'D150 Club', 'v8', 'bensiin', 755, '/purus.xml');
insert into autod (mark, model, engine, fuel, price, image) values ('Infiniti', 'Q', 'v6', 'gaas', 401, '/justo/sit/amet/sapien.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Dodge', 'Viper', 'v8', 'diisel', 738, '/bibendum/imperdiet/nullam/orci.js');
insert into autod (mark, model, engine, fuel, price, image) values ('Lincoln', 'Blackwood', 'v8', 'bensiin', 325, '/ut.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Infiniti', 'FX', 'v6', 'bensiin', 437, '/luctus/et/ultrices/posuere/cubilia/curae/nulla.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Panoz', 'Esperante', 'v12', 'diisel', 362, '/venenatis/lacinia/aenean/sit/amet/justo.json');
insert into autod (mark, model, engine, fuel, price, image) values ('Honda', 'Accord', 'v8', 'gaas', 224, '/mattis/pulvinar/nulla/pede.png');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'Mustang', 'v12', 'elekter', 655, '/lacinia.jsp');
insert into autod (mark, model, engine, fuel, price, image) values ('Ford', 'F350', 'v12', 'diisel', 929, '/molestie/lorem.aspx');
