insert into cars (mark, model, engine, fuel, price, image) values ('Chrysler', 'Concorde', 'V12', 'gaas', 6072, '/pede.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Isuzu', 'Amigo', 'V12', 'bensiin', 7046, '/rutrum/at/lorem/integer/tincidunt/ante/vel.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Kia', 'Spectra5', 'V8', 'diisel', 3613, '/velit/nec/nisi/vulputate/nonummy/maecenas.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Plymouth', 'Colt Vista', 'V6', 'gaas', 9026, '/pretium/quis/lectus/suspendisse/potenti.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'E-Class', 'V12', 'elekter', 3121, '/interdum.json');
insert into cars (mark, model, engine, fuel, price, image) values ('MINI', 'Cooper', 'V12', 'gaas', 2302, '/vestibulum/aliquet/ultrices/erat/tortor/sollicitudin.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Maybach', '62', 'V6', 'diisel', 8109, '/ut.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'E-Class', 'V6', 'elekter', 7795, '/nisl/ut/volutpat/sapien/arcu/sed/augue.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Express 2500', 'V12', 'elekter', 898, '/eu/magna/vulputate/luctus/cum.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Corbin', 'Sparrow', 'V12', 'bensiin', 2017, '/leo/maecenas/pulvinar.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Express 3500', 'V12', 'diisel', 8478, '/amet.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Jeep', 'Cherokee', 'V6', 'gaas', 3800, '/id/sapien/in.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Jeep', 'Cherokee', 'V12', 'gaas', 3925, '/consequat.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'D350 Club', 'V12', 'bensiin', 6410, '/nisl/venenatis.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'S10 Blazer', 'V8', 'elekter', 8191, '/sapien/ut/nunc/vestibulum/ante.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercedes-Benz', 'W201', 'V12', 'elekter', 8510, '/et/ultrices.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Toyota', 'Avalon', 'V12', 'bensiin', 2274, '/id/mauris/vulputate/elementum/nullam/varius.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Mazda', 'Familia', 'V6', 'gaas', 2129, '/condimentum/id/luctus/nec/molestie.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Lexus', 'SC', 'V12', 'elekter', 6069, '/imperdiet/sapien.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Honda', 'Accord', 'V6', 'elekter', 3491, '/lacus/at/velit/vivamus/vel/nulla.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Honda', 'Passport', 'V6', 'diisel', 6103, '/libero/convallis/eget.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Jetta', 'V8', 'diisel', 8795, '/in.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Honda', 'Accord', 'V8', 'diisel', 1237, '/ut/odio/cras.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Fiat', 'Nuova 500', 'V8', 'elekter', 6019, '/tempus/vel/pede/morbi.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Chevrolet', 'Malibu', 'V6', 'elekter', 5834, '/sapien/dignissim.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Volkswagen', 'Golf', 'V6', 'bensiin', 2814, '/in.jpg');
insert into cars (mark, model, engine, fuel, price, image) values ('Audi', 'R8', 'V8', 'gaas', 6889, '/rutrum/nulla.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Cadillac', 'Escalade EXT', 'V12', 'elekter', 2270, '/vivamus/metus/arcu/adipiscing/molestie.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Nissan', 'Murano', 'V12', 'gaas', 7512, '/tempus/sit/amet.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('BMW', 'Alpina B7', 'V8', 'gaas', 5972, '/nec.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Audi', '90', 'V8', 'diisel', 5185, '/in/sagittis.json');
insert into cars (mark, model, engine, fuel, price, image) values ('Eagle', 'Vision', 'V6', 'diisel', 6278, '/lorem/vitae/mattis/nibh/ligula/nec.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Bentley', 'Mulsanne', 'V6', 'bensiin', 3397, '/primis/in/faucibus/orci/luctus.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Lancer Evolution', 'V6', 'diisel', 9022, '/venenatis/lacinia.html');
insert into cars (mark, model, engine, fuel, price, image) values ('Mitsubishi', 'Eclipse', 'V8', 'elekter', 5392, '/convallis/nulla/neque/libero/convallis.js');
insert into cars (mark, model, engine, fuel, price, image) values ('Mercury', 'Tracer', 'V12', 'elekter', 4111, '/amet.jsp');
insert into cars (mark, model, engine, fuel, price, image) values ('Oldsmobile', 'Bravada', 'V12', 'gaas', 6908, '/at/velit/vivamus.aspx');
insert into cars (mark, model, engine, fuel, price, image) values ('Dodge', 'Ram 1500', 'V12', 'diisel', 2316, '/leo/maecenas/pulvinar.png');
insert into cars (mark, model, engine, fuel, price, image) values ('Audi', '100', 'V12', 'bensiin', 5141, '/quam/pharetra/magna/ac/consequat/metus/sapien.xml');
insert into cars (mark, model, engine, fuel, price, image) values ('Ferrari', '458 Italia', 'V6', 'elekter', 1023, '/ultrices/enim/lorem.js');
